### ISSUE TITLE
Keys only build

### ISSUE THREAD

**Issue by faurehu** [dbieber/GoNoteGo#38]
Can you please modify the instructions for those who want to build one just to type in? I presume buying the RasPi 400 should be enough.

**Comment by dbieber** [comment]
100%.
You should be able to get 90% of the value of Go Note Go with just a Raspberry Pi 400. This will enable note-taking, GNG's core feature.

For commands like :t (read the time aloud) and :r (read back the last note you took), you'll need a speaker; any USB or bluetooth speaker or headphones will do.

If you want to take audio notes, I recommend a [tiny USB microphone](https://www.adafruit.com/product/3367). I no longer recommend using the adafruit voice bonnet as the docs originally read.

The Big Red Button is of course completely optional :), and in fact I haven't used it myself in a long time.

#39 updates the docs to reflect these latest hardware recommendations.

If you run into trouble getting set up, don't hesitate to ask qs in GitHub Issues.

**Comment by faurehu** [comment]
Thank you!
